# Generated by Django 6.0.5 on 2026-05-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_last_accessed_enrollment_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment Verification'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
